### PR TITLE
165273529: User sign in feature

### PR DESCRIPTION
**Pull request by kalsmic**
**What does this PR do?**

- Implements user sign in

**Description of Task to be completed?**

- [x] Design Login page Mock
- [x] create login actions
- [x] test login actions
- [x] create login in reducer
- [x] test login reducer
- [x] create login in  form component
- [x] test login  form component
- [x] Design login form css
- [x] render login  modal component

**How should this be manually tested?**

- Navigate to the [login route](https://ah-frontend-dojo-pr-16.herokuapp.com/) and login with `{ email: ahbackenddojo@gmail.com, password: Pa$$word123}`

**Any background context you want to provide?**

- Still working on testing the login actions and login component and the main challenge is with mocking API requests with axios.

**What are the relevant pivotal tracker stories?**

- [#165273529](https://www.pivotaltracker.com/story/show/165273529)

**Screenshots (if appropriate)**

- Login page
Screenshot 2019-06-12 at 09 26 52

### CODE REVIEW

**Review by nadralia — COMMENTED** [review]
@kalsmic Nice Work, but we still have abnormal behavior on the login and signup, this happens when I click on any of the buttons and close the model , then after try to open the login modal again. i will fail to open. on Console this is the error we get `Uncaught TypeError: Cannot read property 'id' of null
    at HTMLSpanElement`

**Review by bisonlou — CHANGES_REQUESTED** [review]
Good work @kalsmic Please remember that booleans begin with an is. eg `PropType.string.isRequired`. So if you do not mind, kindly change `submitted` to `isSubmitted`.

**Review by llwasampijja — CHANGES_REQUESTED** [review]
Nice work @kalsmic On the implementation of the login feature. However, It would be better if you add an image of the sign in form for the front end application.

**Comment by kalsmic** [comment]
> Good work @kalsmic Please remember that booleans begin with an is. eg `PropType.string.isRequired`. So if you do not mind, kindly change `submitted` to `isSubmitted`.

Thanks, @bisonlou, I have changed the variable naming accordingly

**Comment by kalsmic** [comment]
> @kalsmic Nice Work, but we still have abnormal behavior on the login and signup, this happens when I click on any of the buttons and close the model , then after try to open the login modal again. i will fail to open. on Console this is the error we get `Uncaught TypeError: Cannot read property 'id' of null at HTMLSpanElement`

@nadralia, I have checked out this issue but still do not know how to fix it. let me go through the code again. Any ideas on how to fix it are highly welcome

**Review by llwasampijja — APPROVED** [review]

**Comment by kalsmic** [comment]
> @kalsmic Nice Work, but we still have abnormal behavior on the login and signup, this happens when I click on any of the buttons and close the model , then after try to open the login modal again. i will fail to open. on Console this is the error we get `Uncaught TypeError: Cannot read property 'id' of null at HTMLSpanElement`

@nadralia, this issue had now been fixed

**Review by bisonlou — APPROVED** [review]

**Review by nadralia — APPROVED** [review]

**Review by JamesMudidi — APPROVED** [review]
I have tested and am currently working on top of your work and its working seamlessly

**Review by ZackAtama — APPROVED** [review]

**Pull request merged**
