### PR TITLE
165273521: Chore setup router dom

### PR DESCRIPTION
**Pull request by JamesMudidi**
**What does this PR do?**

- Setup React Router DOM

**Description of Task to be completed?**

- Set up of the browser dom for react router dom
- Add error route
- Add login route
- Add landing route

**How should this be manually tested?**

Visit the [review app](https://ah-frontend-dojo-pr-14.herokuapp.com/) to test the application
Use the following routes:
- `/` for the landing page
- `/login` for the login page
- To visit the error route visit a non-existing route

**Any background context you want to provide?**

- We are using the router dom to navigate between different components, changing the browser URL, modifying the browser history, and keeping the UI state in sync.
- Since we are having two working routes, it's good that we have an error route as well which is invoked when a non-existing route is passed on our application

**What are the relevant pivotal tracker stories?**

- [165273521](https://www.pivotaltracker.com/story/show/165273521)

**Screenshots (if appropriate)**
Home page
Screenshot 2019-05-30 at 7 37 06 AM

Login page
Screenshot 2019-05-29 at 8 33 10 PM

Error page
Screenshot 2019-05-30 at 7 36 12 AM

### CODE REVIEW

**Review by bisonlou — CHANGES_REQUESTED** [review]
Great work @JamesMudidi. Thanks for the resilience to work on this task after going through several blockers. However, I notice you have 3 commits. This wouldn't be a problem if they were unique and meaningful. So kindly squash the commits, or make them unique and meaningful.

**Comment by JamesMudidi** [comment]
> Great work @JamesMudidi. Thanks for the resilience to work on this task after going through several blockers. However, I notice you have 3 commits. This wouldn't be a problem if they were unique and meaningful. So kindly squash the commits, or make them unique and meaningful.

I have implemented the requested changes @bisonlou

**Review by bisonlou — DISMISSED** [review]

**Comment by kalsmic** [comment]
Well done @JamesMudidi, I have tested the feature and It works fine.

**Review by bisonlou — DISMISSED** [review]
@JamesMudidi. Please work on your PR heading. Try `165273521: Chore setup router dom `

**Review by llwasampijja — CHANGES_REQUESTED** [review]
nice work @JamesMudidi on the implementation of the router dom, as well as the tests. It would also be better if you change the name of the tests file names for the login and home components to be similar to the corresponding components names!

**Review by nadralia — APPROVED** [review]

**Review by llwasampijja — APPROVED** [review]

**Review by kalsmic — APPROVED** [review]
well done @JamesMudidi

**Review by ZackAtama — APPROVED** [review]
Well done James.

**Review by bisonlou — APPROVED** [review]
Great work @JamesMudidi.

**Pull request merged**
