### PR TITLE
#166282663: Deploy the app to heroku

### PR DESCRIPTION
**Pull request by bisonlou**
**What does this PR do?**

 - Provides necessary settings to facilitate app deployment to Heroku.

**Description of Task to be completed?**

- Create files and configurations necessary to deploy an app on Heroku.

**How should this be manually tested?**

- Visit the [review app](https://ah-frontend-dojo-pr-11.herokuapp.com/).

**Any background context you want to provide?**

- We are currently hosting our apps locally, but for demonstration and testing purposes. It is imperative 
   that we deploy our app to a hosting server.

**What are the relevant pivotal tracker stories?**

- [166282663](https://www.pivotaltracker.com/n/projects/2326197)

**Screenshots (if appropriate)**
image

### CODE REVIEW

**Review by kalsmic — APPROVED** [review]
well done @bison, however, I think we should migrate the app to another account that has room for more pipelines because the maximum number of apps you can have on a free Heroku account is 5 and I believe you already have other apps on your account.

**Review by nadralia — COMMENTED** [review]
Good Work @bisonlou. Could you also add the Heroku Url to the readme for easy access?

**Review by nadralia — APPROVED** [review]

**Review by ZackAtama — APPROVED** [review]
Good work @bisonlou, though as suggested by @nadralia, it would be great to have the heroku url in the readme.

**Review by llwasampijja — APPROVED** [review]
Nice implementation of Heroku deployment. @bisonlou. I have tested it and seems to work fine on Heroku.

**Review by JamesMudidi — APPROVED** [review]
Having tested the Heroku link, I approve th echanges

**Pull request merged**
