### PR TITLE
#165273515: Adding hound GitHub integration

### PR DESCRIPTION
**Pull request by llwasampijja**
**What does this PR do?**

- Adds hound-GitHub integration

**Description of Task to be completed?**

- Integrate houndci into repo

**How should this be manually tested?**

- Can be tested by making a pull request and then check it out.

**Any background context you want to provide?**

- None

**What are the relevant pivotal tracker stories?**

- [#165273515](https://www.pivotaltracker.com/story/show/165273515)

**Screenshots (if appropriate)**

- 
Screenshot 2019-05-29 at 15 13 48

### CODE REVIEW

**Review by bisonlou — APPROVED** [review]
Good work @llwasampijja.

**Review by nadralia — CHANGES_REQUESTED** [review]
Nice Work @llwasampijja could we also cater for scss files

**Review by kalsmic — APPROVED** [review]
Well done @llwasampijja.

**Review by nadralia — APPROVED** [review]
Good Work @llwasampijja

**Review by kcharles52 — APPROVED** [review]

**Review by JamesMudidi — APPROVED** [review]
@llwasampijja, Nice work.

**Pull request merged**
