### PR TITLE
#165273519: Setup environment for writing tests

### PR DESCRIPTION
**Pull request by nadralia**
### What does this PR do?
Setup environment for writing tests
### Description of Task to be completed?
Setup environment for writing tests
### How should this be manually tested?

- Clone the repo or checkout to this branch
- Install dependencies: `npm install`
- run tests : `npm test`
- Coverage: `npx jest --coverage`

### Any background context you want to provide?
None

### What are the relevant pivotal tracker stories?
#165273519

### Screenshots (if appropriate)

Screenshot 2019-05-28 at 18 27 29

### CODE REVIEW

**Review by kalsmic — APPROVED** [review]
well done, @nadralia

**Review by ZackAtama — APPROVED** [review]
Great work with the tests setup, @nadralia.

**Review by JamesMudidi — APPROVED** [review]
Thanks @nadralia this will help us with the tests.
I have tested it locally and it works seamlessly

**Review by llwasampijja — APPROVED** [review]
@nadralia nice implementation on setting up the environment for writing tests. Conventions observed. Also tested running the tests, eslint and everything seems to fine!

**Review by bisonlou — APPROVED** [review]
Well done @nadralia. I have been able to run the tests.

**Comment by kcharles52** [comment]
@nadralia Please remove [Maintains #165273519] in the PR description

**Comment by nadralia** [comment]
> @nadralia Please remove [Maintains #165273519] in the PR description

Done

**Pull request merged**
