### PR TITLE
166266384: Setup pre-commit and pre-push hooks 

### PR DESCRIPTION
**Pull request by kalsmic**
**What does this PR do?**
- Sets up pre-push and pre-commit hooks

**Description of Task to be completed?**

 - Set up pre-commit
    - Runs eslint and fix for staged files
   -  Runs style lint and fixes issues for staged files
   - Stages the changes
 - setup pre-push hooks.
     - Run eslint
     - Run stylelint
     - Run tests
     
 - set up commit lint to check the commit message
    - Runs a check for the commit message format.

**How should this be manually tested?**
- View the screenshots for pre-push and pre-commit in action.

**Any background context you want to provide?**

- The expected format of the commit message
```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

**What are the relevant pivotal tracker stories?**

- [#166266384](https://www.pivotaltracker.com/story/show/166266384)

**Screenshots (if appropriate)**

Screenshot 2019-05-30 at 18 46 30
Screenshot 2019-05-30 at 18 54 01

### CODE REVIEW

**Review by nadralia — APPROVED** [review]

**Review by llwasampijja — APPROVED** [review]
Nice work @kalsmic, I have run eslint, and the tests are still passing, Great job at that. I have tested the feature and it works as expected as I can't commit with the wrong commit message as well as when there are any eslint errors. I have also tried the feature on my local machine and it is still running well. I also deployed it on Heroku, and it is working fine as well.
nice work once again!

**Review by JamesMudidi — APPROVED** [review]
Nice work @kalsmic.
Having run all the relevant tests, the feature works as expected.

**Review by ZackAtama — APPROVED** [review]
All tests pass, good work @kalsmic

**Review by bisonlou — APPROVED** [review]
Ingenious work @kalsmic. I have gone through the PR and indeed it runs the linter and tests before pushing and on committing. Well done.

**Review by kcharles52 — APPROVED** [review]

**Pull request merged**
