### PR TITLE
#166280143 Add  Pull request template

### PR DESCRIPTION
**Pull request by llwasampijja**
**What does this PR do?**

Adds pull request template

**Description of Task to be completed?**

Add a pull request template that can be used by all the team members for purposes of maintaining consistency pull requests.

**How should this be manually tested?**

checkout ah-frontend-dojo/docs/pull_request_template.md

**Any background context you want to provide?**

None

**What are the relevant pivotal tracker stories?**

[#166280143](https://www.pivotaltracker.com/story/show/166280143)

**Screenshots (if appropriate)**
 None

### CODE REVIEW

**Comment by ZackAtama** [comment]
Good work with adding the pull request template @llwasampijja

**Review by ZackAtama — APPROVED** [review]

**Review by nadralia — APPROVED** [review]
@llwasampijja  Nice work

**Review by bisonlou — APPROVED** [review]
Weldone @llwasampijja. This looks good. I have checked out the repo and it does exist in the docs folder. This will give us a good foundation for our PR descriptions.

**Review by JamesMudidi — APPROVED** [review]
After Implementing the recommended changes, I tested it locally and it works as expected

**Comment by kalsmic** [comment]
@llwasampijja, I would like to seek clarity on this, based on the [resource](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) that @kcharles52 shared in slack, looking at the section that says,
> To make your pull request template visible in the repository's docs directory, type docs/, then the name of your pull request template. For example, docs/pull_request_template.md.`

Does this refer to the point when some else is creating the PR or does the title for this pull request have to conform to what has been specified above?

**Comment by kcharles52** [comment]
> @llwasampijja, I would like to seek clarity on this, based on the [resource](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) that @kcharles52 shared in slack, looking at the section that says,
> 
> > To make your pull request template visible in the repository's docs directory, type docs/, then the name of your pull request template. For example, docs/pull_request_template.md.`
> 
> Does this refer to the point when some else is creating the PR or does the title for this pull request have to conform to what has been specified above?

@kalsmic the description in the slack channel is for the name not the description of the PR, the template gives the description of the PR and the communication in the slack channel refers to the PR title

**Review by kalsmic — APPROVED** [review]

**Pull request merged**
